#!/usr/bin/awk -f
# latex_export.awk
# Genera un archivo LaTeX listo para compilar con bibliografia automatica.
# Incluye seccion Related Work con \cite{} y archivo .bib generado.
#
# Uso: awk -f latex_export.awk stage3_scored.tsv > RELATED_WORK.tex

BEGIN {
    FS = OFS = "\t"

    print "% Literature Pipeline - LaTeX Export"
    print "% Compilar con: pdflatex RELATED_WORK.tex && bibtex RELATED_WORK && pdflatex RELATED_WORK.tex"
    print ""
    print "\\documentclass[11pt,a4paper]{article}"
    print "\\usepackage[utf8]{inputenc}"
    print "\\usepackage[T1]{fontenc}"
    print "\\usepackage{hyperref}"
    print "\\usepackage{booktabs}"
    print "\\usepackage{longtable}"
    print "\\usepackage{xcolor}"
    print "\\usepackage{tikz}"
    print "\\usetikzlibrary{shapes,arrows,positioning}"
    print ""
    print "\\begin{document}"
    print ""
    print "\\title{Related Work — Automatic Generation}"
    print "\\author{Literature Pipeline v4.0}"
    print "\\date{\\today}"
    print "\\maketitle"
    print ""
    print "\\section{Introduction}"
    print "This document was automatically generated by the Literature Pipeline."
    print "It includes a curated list of papers, their scores, and a narrative"
    print "overview of the research landscape."
    print ""
    print "\\section{Core Papers}"
    print ""
    print "\\begin{longtable}{llllr}"
    print "\\toprule"
    print "\\textbf{Author} & \\textbf{Year} & \\textbf{Title} & \\textbf{DOI} & \\textbf{Score} \\\\"
    print "\\midrule"
    print "\\endfirsthead"
    print "\\toprule"
    print "\\textbf{Author} & \\textbf{Year} & \\textbf{Title} & \\textbf{DOI} & \\textbf{Score} \\\\"
    print "\\midrule"
    print "\\endhead"
    print "\\bottomrule"
    print "\\endfoot"
}

NR == 1 { next }

{
    doi = $1
    title = $2
    year = $3
    authors = $4
    score = $8

    # Extraer primer apellido para cite key
    first_author = authors
    sub(/,.*/, "", first_author)
    sub(/ .*/, "", first_author)
    gsub(/[^a-zA-Z]/, "", first_author)
    cite_key = tolower(first_author) year

    # Escapar LaTeX en titulo
    gsub(/&/, "\\&", title)
    gsub(/%/, "\\%", title)
    gsub(/\$/, "\\$", title)
    gsub(/#/, "\\#", title)
    gsub(/_/, "\\_", title)

    # Acortar titulo para tabla
    if (length(title) > 40)
        title = substr(title, 1, 40) "..."

    # Acortar autores
    if (authors ~ /,.*,/) {
        first = authors
        sub(/,.*/, "", first)
        authors = first " et al."
    }

    print "  " authors " & " year " & " title " & \\href{https://doi.org/" doi "}{" doi "} & " score " \\\\"

    # Guardar para .bib
    bib_title[NR] = $2  # titulo original sin escapar
    bib_author[NR] = $4
    bib_year[NR] = $3
    bib_doi[NR] = $1
    bib_key[NR] = cite_key
}

END {
    print "\\end{longtable}"
    print ""
    print "\\section{Narrative Overview}"
    print ""
    print "The following paragraphs provide a thematic overview of the selected literature."
    print ""

    # Generar parrafos tematicos simples
    print "\\subsection{Foundational Work}"
    print "Several foundational papers have shaped this research area."
    for (i = 2; i <= NR; i++) {
        if (bib_year[i] + 0 <= 2018) {
            print "\\cite{" bib_key[i] "} introduced key concepts that remain influential."
        }
    }
    print ""

    print "\\subsection{Recent Advances}"
    print "More recent work has built upon these foundations."
    for (i = 2; i <= NR; i++) {
        if (bib_year[i] + 0 >= 2022) {
            print "\\cite{" bib_key[i] "} presents state-of-the-art results."
        }
    }
    print ""

    print "\\bibliographystyle{plain}"
    print "\\bibliography{literature_pipeline}"
    print ""
    print "\\end{document}"
    print ""

    # Generar archivo .bib
    bib_file = "literature_pipeline.bib"
    print "\\begin{filecontents}{" bib_file "}" > bib_file
    for (i = 2; i <= NR; i++) {
        print "@article{" bib_key[i] "," >> bib_file
        print "  title={" bib_title[i] "}," >> bib_file
        print "  author={" bib_author[i] "}," >> bib_file
        print "  year={" bib_year[i] "}," >> bib_file
        print "  doi={" bib_doi[i] "}," >> bib_file
        print "  url={https://doi.org/" bib_doi[i] "}" >> bib_file
        print "}" >> bib_file
        print "" >> bib_file
    }
    print "\\end{filecontents}" >> bib_file
    close(bib_file)

    print "% BibTeX file generated: " bib_file
}
