#!/usr/bin/awk -f
# zettel_generator.awk
# Genera notas atómicas (Zettel) para Obsidian / Zettelkasten
# Una nota por paper, con links bidireccionales [[...]]
#
# Uso: awk -f zettel_generator.awk stage3_scored.tsv
# (genera archivos en ./zettel/)

BEGIN {
    FS = OFS = "\t"

    # Crear directorio de salida
    system("mkdir -p zettel")

    print "# Zettel Generator"
    print "Generando notas atómicas en ./zettel/"
    print ""
}

NR == 1 { next }

{
    doi = $1
    title = $2
    year = $3
    authors = $4
    abstract = $5
    sources = $6
    seed = $7
    score = $8
    sup = $9
    cont = $10
    tot = $11
    ratio = $12

    # Crear nombre de archivo: primer-apellido-year.md
    # Extraer primer apellido del primer autor
    first_author = authors
    sub(/,.*/, "", first_author)
    sub(/ .*/, "", first_author)  # quitar iniciales
    gsub(/[^a-zA-Z]/, "", first_author)

    filename = tolower(first_author) "-" year ".md"
    filepath = "zettel/" filename

    # Generar tags desde keywords del abstract
    tags = ""
    abst_lower = tolower(abstract)
    if (abst_lower ~ /transformer|attention/) tags = tags " transformer"
    if (abst_lower ~ /bert|pre-training|pretraining/) tags = tags " bert"
    if (abst_lower ~ /gpt|language model|llm/) tags = tags " llm"
    if (abst_lower ~ /gan|generative|adversarial/) tags = tags " gan"
    if (abst_lower ~ /residual|resnet|cnn/) tags = tags " cnn"
    if (abst_lower ~ /survey|review/) tags = tags " survey"
    if (abst_lower ~ /chain-of-thought|reasoning/) tags = tags " reasoning"
    if (abst_lower ~ /retrieval|augmented|rag/) tags = tags " rag"
    if (abst_lower ~ /scaling|emergence|few-shot/) tags = tags " scaling"
    if (abst_lower ~ /ethical|bias|environmental|risk/) tags = tags " ethics"

    # Limpiar tags
    gsub(/^[ \t]+/, "", tags)

    # Generar contenido de la nota
    note = "---\n"
    note = note "title: \"" title "\"\n"
    note = note "doi: " doi "\n"
    note = note "year: " year "\n"
    note = note "authors: \"" authors "\"\n"
    note = note "score: " score "\n"
    note = note "seed: " (seed == "YES" ? "true" : "false") "\n"
    note = note "sources: " sources "\n"
    note = note "scite_supporting: " sup "\n"
    note = note "scite_contrasting: " cont "\n"
    note = note "scite_total: " tot "\n"
    note = note "scite_ratio: " ratio "\n"
    note = note "tags:" tags "\n"
    note = note "---\n\n"

    note = note "# " title "\n\n"
    note = note "> **" authors "** | *" year "* | [DOI](https://doi.org/" doi ")\n\n"

    note = note "## Abstract\n\n"
    note = note abstract "\n\n"

    note = note "## Key Claims\n\n"
    note = note "- [ ] Claim 1: _extract from paper_\n"
    note = note "- [ ] Claim 2: _extract from paper_\n"
    note = note "- [ ] Claim 3: _extract from paper_\n\n"

    note = note "## Methods\n\n"
    note = note "- _Methodology used in this paper_\n\n"

    note = note "## Results\n\n"
    note = note "- _Key results and metrics_\n\n"

    note = note "## Connections\n\n"
    note = note "### Cited By (papers that cite this one)\n"
    note = note "- [[_paper-that-cites-this_]]\n\n"

    note = note "### Cites (papers this one references)\n"
    note = note "- [[_ foundational-paper_]]\n\n"

    note = note "### Related\n"
    note = note "- [[_similar-approach-paper_]]\n\n"

    note = note "## Notes\n\n"
    note = note "- **Relevance Score**: " score "/10\n"
    note = note "- **Scite Confidence**: " ratio " (" sup " supporting / " tot " total)\n"
    note = note "- **Contradictions**: " cont " papers contradict this work\n"
    note = note "- **Sources**: " sources "\n"
    note = note "- **Status**: " (seed == "YES" ? "🌱 Seed paper — high priority" : "Regular candidate") "\n\n"

    note = note "## Quotes\n\n"
    note = note "> _Add memorable quotes here_\n\n"

    note = note "---\n"
    note = note "*Generated by literature-pipeline* | " (ENVIRON["SOURCE_DATE_EPOCH"] != "" ? ENVIRON["SOURCE_DATE_EPOCH"] : systime())

    # Escribir archivo
    print note > filepath
    close(filepath)

    print "✓ " filepath
    generated[doi] = filename
}

END {
    print ""
    print "---"
    print "Total zettels generados: " length(generated)
    print ""
    print "## Index de Zettels"
    print ""
    print "| # | Zettel | DOI |"
    print "|---|--------|-----|"

    idx = 0
    for (d in generated) {
        idx++
        print "| " idx " | [[" generated[d] "]] | " d " |"
    }

    print ""
    print "## Consejos de uso en Obsidian"
    print ""
    print "1. Copia la carpeta `zettel/` a tu vault de Obsidian."
    print "2. Usa el graph view para ver conexiones entre papers."
    print "3. Completa las secciones 'Key Claims', 'Methods', 'Results' a medida que lees."
    print "4. Agrega links bidireccionales manualmente: `[[autor-year]]`."
    print "5. Filtra por tag: `#llm` o `#transformer` en el search."
}
